import { ScratchProvider } from "@/providers/scratch";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Template  Builder",
  description: "Generated by cPelz",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ScratchProvider>{children}</ScratchProvider>;
}
